### ISSUE TITLE
How can we use Webix with React and Meteor?

### ISSUE THREAD

**Issue by wuxianliang** [dandv/meteor-webix#11]
Sorry, just a question. I have no idea about it. But wish we could. Thank you very much!

**Comment by ghost** [comment]
You could use Webix widget the same way as you use jQuery widgets in React.
Similar to https://github.com/petehunt/react-jqueryui/blob/master/src/index.js I guess.

As far as I know Webix widget don't support the reactive model very well. That means either you need to rerender the whole thing when you change data or you need to write a data proxy that translates a data diff to calls of `add`, `remove`, `change` etc. Because Webix mainly uses the data binding technique.

**Comment by wuxianliang** [comment]
Thank you very much!
